### ISSUE TITLE
Webhook Sentry might be deleting request body somehow?

### ISSUE THREAD

**Issue by mlissner** [juggernaut/webhook-sentry#15] opened 2023-04-27 19:32 UTC
This one is a long shot, but we're pretty baffled about it, so I'm writing it down here in case it rings a bell with you, @juggernaut, or perhaps somebody else. 

We're using Webhook Sentry in a k8s environment. Every so often, a request goes into Webhook Sentry with a request body, but arrives at our webhook endpoint without it. Somewhere along the line the request body is being stripped.

The full process looks like this:
1. Our application layer creates a webhook POST with a body.
2. An assertion is checked just before the next step, to ensure the request has a body.
3. The request is posted to Webhook Sentry, which proxies it to our webhook endpoint of a different service.
4. Our webhook endpoint checks `request.json`, but it's empty.
5. Our webhook endpoint therefore crashes and throws an HTTP error.
6. The application layer from step 1 catches the error and retries the webhook.
7. It works.

We aim to send a high volume of webhook events, so we want to track this down. After having this error happen a few times, we put an assertion at step 2 above to make sure that we weren't sending empty bodies. Today, we had the error happen again, meaning that the assertion passed, but somehow the webhook endpoint didn't get data on step 4.

I'm entirely open to the possibility that there's something in our network layer causing this, but:
 - It would be weird for an encrypted request to be modified in transit.
 - We don't have anything particularly weird in our network layer.

We're at a bit of a loss. Data is going into the network OK—it passes the assertion—but is somehow vanishing along the way. Does this make any sense to you or maybe ring any bells? Is it something that a bug in Webhook Sentry could cause? 

If you have any ideas for how to look into this, we'd be happy to try to help debug/fix it. We're motivated on this one! Thank you! 

We're tracking [the issue here](https://github.com/freelawproject/bigcases2/issues/128).

**Comment by juggernaut** [comment] 2023-04-27 20:14
That seems strange @mlissner . I haven't encountered this issue so far. So that I can attempt to reproduce on my end, can you please provide the following info:
1. Headers and request params passed to webhook-sentry
2. Approximate size of request body
3. webhook-sentry config
4. Does it happen only under load, or even when there is zero to no load?

Thanks!

**Comment by albertisfu** [comment] 2023-04-27 21:47
Thanks @juggernaut  here are the details about the issue:

> 1.- Headers and request params passed to webhook-sentry:

These are the headers we're sending to webhook proxy:
```
"Content-type": "application/json"
"Idempotency-Key": An uuid string used by the client to identify the uniqueness of the request.
"X-WhSentry-TLS": "true"
```

And the request is made with the following params:

We're using Python `requests` module:

```
proxy_server = {
        "http": "http://cl-webhook-sentry:9090",  #The proxy URL.
    }
requests.post(
            url,
            proxies=proxy_server,
            json=json_data,
            timeout=(3, 3),
            stream=True,
            headers=headers,
            allow_redirects=False,
        )
```

The `url` param here is changed in order to use the `http` protocol as described in [documentation](https://github.com/juggernaut/webhook-sentry#https-target) 

> 2. Approximate size of request body

Here are some sizes of the request body from different events that failed:

8,551 bytes
90,293 bytes
18,314 bytes
10,252 bytes
12,278 bytes 
11,841 bytes

In the end, events usually succeed after some retries.
I checked many events in which the delivery succeeded on the first attempt, and the average size is approximately 3,000 bytes. Interestingly, I've not encountered an event where this issue occurred with a size of less than 8,000 bytes. It is uncertain whether this is merely a coincidence.

> 3. webhook-sentry config

We're using the docker image` juggernaut/webhook-sentry:v1.1.0` with the default `config.go` file.

In case is helpful this is the k8s config:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cl-webhook-sentry
  namespace: court-listener
  labels:
    service: cl-webhook-sentry
spec:
  replicas: 2
  selector:
    matchLabels:
      service: cl-webhook-sentry
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: cl-webhook-sentry
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: static-egress-node-group
      containers:
        - name: webhook-sentry
          image: juggernaut/webhook-sentry:v1.1.0
          imagePullPolicy: IfNotPresent
          ports:
           - containerPort: 9090
          livenessProbe:
            periodSeconds: 5
            httpGet:
              path: /metrics
              port: 2112


---
apiVersion: v1
kind: Service
metadata:
  name: cl-webhook-sentry
  namespace: court-listener
  labels:
    service: cl-webhook-sentry
spec:
  selector:
    service: cl-webhook-sentry
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090

```

> 4. Does it happen only under load, or even when there is zero to no load?

At the moment, we are not experiencing a high load, as we are sending no more than 15 events per hour. Today's error occurred during a period of low load; it was the only event sent at that time. There was a successful event two minutes prior and another one ten minutes later.


Finally, I'm not sure if this might be related but I noticed a similar issue sending events to an HTTPS `ngrok` endpoint using `webhook-sentry` with `X-WhSentry-TLS` header set to True, the headers are properly received but the data is empty.


Thank you!

**Comment by juggernaut** [comment] 2023-04-28 07:32
Thanks for the details @albertisfu ! I'll take a look tomorrow and get back to you. Also, just to confirm, you're not using ngrok in your production setup right? The issue with ngrok is when you were doing dev stuff locally I presume?

**Comment by albertisfu** [comment] 2023-04-28 15:14
Thank you! yes, `ngrok` is not used in production, I noticed the issue doing some dev testing.

**Comment by juggernaut** [comment] 2023-05-01 20:27
@albertisfu @mlissner I tried reproducing with different request body sizes (and with ngrok in the request path), but could not reproduce it. I was using a flask app as the target server. However, I did notice that webhook-sentry is always sending a `Transfer-Encoding: chunked` instead of the `Content-Length` header even when its available on the input request. 

Going through your linked ticket, it appears you are using Django which according to cursory googling may have issues dealing with chunked encoding (https://stackoverflow.com/questions/12091067/handling-http-chunked-encoding-with-django). Can you share a little bit more about your setup? How does the request path look like, right from the origin to your target webhook receiver? I'm wondering if something along the path "fixes up" the chunked encoding header, but not in all cases, which may explain the intermittent behavior you are seeing. If you an provide a condensed version of your django receiver endpoint that would be a great help as well.

I have a fix for copying over the `Content-Length` header, but I would rather reproduce this issue first to understand the root cause, than just apply a fix without confirming it actually fixes the issue.

**Comment by mlissner** [comment] 2023-05-01 23:36
Thanks so much for supporting your work like this, @juggernaut. 

While Alberto is working on reproducing this, I did a bunch **more googling**. Almost everything I could was, really old, but I did find [a post from earlier this year](https://github.com/benoitc/gunicorn/issues/2947#issue-1586772499) in the gunicorn issue tracker. It says:

> With gunicorn 20.1.0 - when it receives a chunked request - the body is available to the application from wsgi.input but the headers are untouched: the application sees no CONTENT_LENGTH header.
> 
> Is this the intended behaviour? Django for example will return an empty body in this case.

To which a "contributor" to gunicorn replies:

> Yes, this is intentional. Transfer-Encoding: chunked must not set a content length. This is what the wsgi.input_terminated extension to the spec is for, Gunicorn and other WSGI servers set it to indicate that they handle terminating the stream and that it's safe to read. Django does not use this, it does not support streaming request bodies. 

So that feels like a smoking gun, but it's unclear why it only fails *sometimes*.

----

Our full **network architecture** is:

1. Our main server uses Python `requests` to send a POST request (webhook event) to Webhook Sentry (via the code Alberto posted above).
2. Webhook Sentry forwards the request to our other server over the Internet.
3. The other server is behind an AWS Application Load Balancer (AWS ALB).
4. The ALB forwards the request to a kubernetes pod running Gunicorn.
5. Gunicorn, using the [sync workers](https://docs.gunicorn.org/en/stable/design.html#sync-workers), sends the request to Django.
6. Django processes the request, and returns an error.

I don't think it matters, but the main server, Webhook Sentry, and the recipient server are all in the same k8s cluster (though with different namespaces).

----

As for the **steps to reproduce** that Alberto's working on, it's tough because he needs to get Gunicorn set up with a TLS certificate to create a minimal example, but he's working on it.

Thank you again. Feels like you've got a pretty good theory here. Hopefully Alberto can prove it.

**Comment by albertisfu** [comment] 2023-05-02 03:23
@juggernaut, we have created a repository where we've reproduced the error within a Docker environment, making it easy to test and evaluate:

https://github.com/albertisfu/test-wh-sentry

The webhook client uses Django and Gunicorn, while `send-request.py` employs Webhook Sentry as a proxy.

There are some instructions in the repo and you'll be able to view logs similar to these:

![Screenshot 2023-05-01 at 21 15 32](https://user-images.githubusercontent.com/486004/235572245-0d1031eb-8348-44a1-ae33-a712c146fd10.png)

Initially, I believed the issue occurred exclusively when using X-WhSentry-TLS, but it also happens for `http` targets, as in this example.

Please let us know if you require any further information or how can we help.

Thanks.

**Comment by mlissner** [comment] 2023-05-02 21:56
Alberto and I talked about this a bit today and the one remaining piece of the puzzle we don't understand is why it only happens some of the time. Our best theory is that:

 - Webhook Sentry provides the headers you mentioned, @juggernaut. 
 - Sometimes routers along the way tweak the headers to simplify the request, perhaps particularly on small requests.
 - Those tweaked requests fail.
 - We do automatic retries.
 - Different routers are used to forward the packets.
 - Those routers don't tweak the message.
 - It works.

**Comment by juggernaut** [comment] 2023-05-04 06:08
Thanks @albertisfu and @mlissner for creating the docker environment! I was able to reproduce the issue and test the fix as well. It was as expected -- the `Content-Length` header was not being passed along by the proxy. This will be addressed by https://github.com/juggernaut/webhook-sentry/pull/16 . Once it's merged I'll cut a new release.

@mlissner I would agree with your assessment of why it happens only some times. My money is on some instances of the ALB "fixing-up" the content length and some not. We'd need a packet capture on either side of the ALB to figure this out, but probably not worth the trouble since we have the fix now.

Another thing to mention -- you'll want to remove `stream=True` from your `requests.post(..)` call on the client. From an SO answer, `stream=True` sends `Transfer-Encoding: chunked` (but in my testing, I only saw `Content-Length` even when stream=True), so you'd want to disable that out of caution since your server can't handle it.

**Comment by juggernaut** [comment] 2023-05-04 06:27
Release v1.1.1 is out with the fix, please verify that it fixes the issue!

**Comment by mlissner** [comment] 2023-05-04 14:49
Lovely. It's deployed. We won't know for some time if this worked, but we'll keep [the issue](https://github.com/freelawproject/bigcases2/issues/128) open on our end and will report results in a few weeks. 

Thank you again for your work supporting this awesome tool. It's really nice to benefit from the security it provides and there's nothing else like it that I've found.

**Closed** 2023-05-05 02:32 UTC

**Comment by mlissner** [comment] 2023-06-01 20:52
Just to close this loop, it's been about a month since we deployed the updated webhook-sentry pod and we haven't had this issue since. Yay!

**Comment by juggernaut** [comment] 2023-06-05 04:19
Great news @mlissner !
